## 03. NumPy

- N-dimensional array
- Random number generation (random sampling)
- Vectorized operations
- Linear algebra
- Probability distributions
- Statistical analysis
- np.NaN (similar to the Python None, represents a missing/null/non-existent value)

#### 1. Random number generation

In [2]:
# generate and print 100 random number between 0 and 9 using Python standard library random
import random
x = []
for i in range(100):
    x.append(random.randint(0,9))     # Python random standard library generate one random number at a time
print(x)
type(x)

[0, 8, 3, 4, 7, 8, 7, 8, 5, 0, 8, 0, 7, 8, 3, 8, 6, 0, 0, 0, 1, 0, 0, 5, 0, 5, 6, 0, 5, 5, 4, 7, 1, 4, 4, 4, 4, 3, 6, 4, 0, 8, 9, 7, 1, 6, 7, 9, 4, 1, 0, 1, 4, 6, 7, 8, 9, 5, 6, 1, 8, 3, 8, 5, 5, 6, 9, 3, 1, 6, 9, 1, 2, 4, 1, 6, 0, 5, 0, 4, 8, 7, 1, 1, 9, 3, 2, 3, 4, 1, 5, 6, 5, 2, 0, 7, 6, 7, 3, 9]


list

In [3]:
# generate and print 100 random number between 0 and 9 using NumPy
import numpy as np
y = np.random.randint(0,10,100)   # Numpy can generate many random number efficiently
print(y)
type(y)

[7 4 6 3 0 7 3 9 0 3 9 8 0 6 2 5 1 8 5 8 8 1 0 5 7 3 1 1 8 8 1 9 8 0 3 7 3
 1 1 6 2 2 9 8 1 6 5 2 3 1 7 0 2 7 2 7 4 0 4 5 2 4 7 1 3 7 7 8 7 3 7 7 1 8
 6 2 1 8 7 3 3 4 2 1 4 7 7 1 1 2 1 4 6 1 8 1 5 6 8 6]


numpy.ndarray

#### 2. Creation
- create an array from a list
- create an array of randomly generated numbersnp.random.randint()
- create an array using arange(start, stop, step, dtype)
- create an array using np.linspace(start, stop, number of values)

In [4]:
# create an array from a list - method #1
z = np.array(x)
print(z)

[0 8 3 4 7 8 7 8 5 0 8 0 7 8 3 8 6 0 0 0 1 0 0 5 0 5 6 0 5 5 4 7 1 4 4 4 4
 3 6 4 0 8 9 7 1 6 7 9 4 1 0 1 4 6 7 8 9 5 6 1 8 3 8 5 5 6 9 3 1 6 9 1 2 4
 1 6 0 5 0 4 8 7 1 1 9 3 2 3 4 1 5 6 5 2 0 7 6 7 3 9]


In [5]:
# convert a list to an array - method #2
z = np.asarray(x)
print(z)

[0 8 3 4 7 8 7 8 5 0 8 0 7 8 3 8 6 0 0 0 1 0 0 5 0 5 6 0 5 5 4 7 1 4 4 4 4
 3 6 4 0 8 9 7 1 6 7 9 4 1 0 1 4 6 7 8 9 5 6 1 8 3 8 5 5 6 9 3 1 6 9 1 2 4
 1 6 0 5 0 4 8 7 1 1 9 3 2 3 4 1 5 6 5 2 0 7 6 7 3 9]


In [6]:
# create an array of randomly generated numbersnp.random.randint()
z = np.random.randint(0,10,100)  
print(z)

[5 1 9 4 8 6 3 0 6 1 8 9 8 9 8 8 5 5 0 3 8 6 4 6 9 6 8 3 4 7 5 0 2 1 3 0 9
 7 4 8 3 2 8 7 8 9 9 5 6 1 0 4 2 3 4 3 7 2 2 3 5 9 3 7 9 2 0 3 3 3 0 5 6 7
 0 7 1 1 6 9 9 8 8 1 5 1 8 4 1 4 2 9 5 7 3 2 6 6 7 6]


In [7]:
# create an array using arange(start, stop, step, dtype)
z = np.arange(10, 100, 10, np.float64)
print(z)

[10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [8]:
# create an array using np.linspace(start, stop, number of values)
z = np.linspace(10, 20, 5)
print(z)

[10.  12.5 15.  17.5 20. ]


#### 3. Operations
- shape: the structure of the array
- reshape(): change the structure of the array
- ndim: number of dimensions
- size: number of elements
- itemsize: the size in bytes of the element
- dtype: the data type of the element
- \[row,colum\] or \[row\]\[column\]: retrieve an item from an array based on its position

In [14]:
# find out the shape of an array
y.shape

NameError: name 'y' is not defined

In [21]:
a = np.random.randint(0,10,24)
print(a)

[7 1 3 8 8 2 5 1 8 3 4 5 7 1 1 0 5 8 9 0 2 9 2 4]


In [22]:
a.shape

(24,)

In [19]:
import numpy as np

In [16]:
a = a.reshape(4,6)
print(a)

[[7 2 3 3 6 6]
 [9 1 7 3 7 5]
 [3 3 6 1 3 8]
 [7 9 5 6 5 4]]


In [13]:
print(a.shape)

(4, 6)


In [14]:
a.size

24

In [15]:
a.ndim

2

In [16]:
a.itemsize

4

In [17]:
a.dtype

dtype('int32')

In [18]:
# access an element in an array - method #1
a[0,0]

6

In [19]:
# access an element in an array - method #2
a[0][0]

6